owned_names = ["erenshor", "item-tooltips", "semantic-link-picker"]

[[gadgets]]
name = "erenshor"
options = ["ResourceLoader", "default", "hidden", "type=styles"]
sources = ["erenshor.css"]

[[gadgets]]
name = "item-tooltips"
options = ["ResourceLoader", "default", "hidden"]
sources = ["item-tooltips.js"]

[[gadgets]]
name = "semantic-link-picker"
options = ["ResourceLoader", "default", "rights=edit"]
sources = ["semantic-link-picker-core.js", "semantic-link-picker.js", "semantic-link-picker.css"]
