from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from erenshor.application.wiki_inventory.api import MediaWikiInventoryClient
from erenshor.application.wiki_inventory.templates import (
    OwnershipClass,
    classify_template,
    render_ownership_manifest,
    template_inventory_from_api,
)


def load_fixture(name: str) -> dict[str, Any]:
    return json.loads(Path("tests/fixtures/wiki_inventory", name).read_text(encoding="utf-8"))


class RecordedTransport:
    def __init__(self, responses: list[dict[str, Any]]) -> None:
        self._responses = responses
        self.requests: list[dict[str, str]] = []

    def __call__(self, params: dict[str, str]) -> dict[str, Any]:
        self.requests.append(params)
        if not self._responses:
            raise AssertionError(f"unexpected request: {params}")
        return self._responses.pop(0)


def test_client_follows_allpages_continuation() -> None:
    transport = RecordedTransport(
        [
            load_fixture("allpages-page1.json"),
            load_fixture("allpages-page2.json"),
        ]
    )
    client = MediaWikiInventoryClient(api_url="https://example.invalid/api.php", transport=transport)

    templates = client.list_templates()

    assert templates == [
        "Template:Ability",
        "Template:Character",
        "Template:Item",
        "Template:Item/Weapon",
        "Template:Item/doc",
    ]
    assert transport.requests[1]["apcontinue"] == "Item/doc"


def test_client_counts_transclusions_across_continuation() -> None:
    transport = RecordedTransport(
        [
            load_fixture("embeddedin-item-page1.json"),
            load_fixture("embeddedin-item-page2.json"),
        ]
    )
    client = MediaWikiInventoryClient(api_url="https://example.invalid/api.php", transport=transport)

    summary = client.embeddedin_summary("Template:Item")

    assert summary.title == "Template:Item"
    assert summary.total == 3
    assert summary.continued is True
    assert summary.examples == ["Sword of Flames", "Abyssal Plate", "Template:Item/doc"]
    assert transport.requests[1]["eicontinue"] == "10|1183"


def test_classifies_cutover_blocking_public_contracts() -> None:
    entry = classify_template("Template:Item", transclusion_count=501, continued=True)

    assert entry.ownership == OwnershipClass.REPO_OWNED_TEMPLATE
    assert entry.cutover_blocking is True
    assert "root public compatibility template" in entry.notes


def test_classifies_template_support_surfaces() -> None:
    assert classify_template("Template:Item/doc").ownership == OwnershipClass.DOCUMENTATION_TEMPLATE
    assert classify_template("Template:License/CC-BY").ownership == OwnershipClass.LICENSE_TEMPLATE
    assert classify_template("Template:Zone Navbox").ownership == OwnershipClass.NAVBOX_TEMPLATE
    assert classify_template("Template:Item/Weapon").ownership == OwnershipClass.LEGACY_TEMPLATE
    assert classify_template("Template:ItemLink").ownership == OwnershipClass.REPO_OWNED_TEMPLATE
    assert classify_template("Template:Unexpected").ownership == OwnershipClass.UNKNOWN


def test_builds_inventory_from_recorded_api_payloads() -> None:
    transport = RecordedTransport(
        [
            load_fixture("allpages-page1.json"),
            load_fixture("allpages-page2.json"),
            load_fixture("embeddedin-ability-page1.json"),
            load_fixture("embeddedin-character-page1.json"),
            load_fixture("embeddedin-item-page1.json"),
            load_fixture("embeddedin-item-page2.json"),
        ]
    )
    client = MediaWikiInventoryClient(api_url="https://example.invalid/api.php", transport=transport)

    inventory = template_inventory_from_api(client)

    by_title = {entry.title: entry for entry in inventory.entries}
    assert by_title["Template:Item"].cutover_blocking is True
    assert by_title["Template:Item"].transclusion_count == 3
    assert by_title["Template:Character"].cutover_blocking is True
    assert by_title["Template:Character"].transclusion_count == 2
    assert by_title["Template:Item/Weapon"].ownership == OwnershipClass.LEGACY_TEMPLATE


def test_renders_deterministic_ownership_manifest() -> None:
    transport = RecordedTransport(
        [
            load_fixture("allpages-page1.json"),
            load_fixture("allpages-page2.json"),
            load_fixture("embeddedin-ability-page1.json"),
            load_fixture("embeddedin-character-page1.json"),
            load_fixture("embeddedin-item-page1.json"),
            load_fixture("embeddedin-item-page2.json"),
        ]
    )
    client = MediaWikiInventoryClient(api_url="https://example.invalid/api.php", transport=transport)

    manifest = render_ownership_manifest(template_inventory_from_api(client))

    assert manifest.startswith("# Generated by `erenshor wiki inventory-templates`.")
    assert "generated_at: null" in manifest
    assert "title: Template:Item" in manifest
    assert "ownership: repo_owned_template" in manifest
    assert "cutover_blocking: true" in manifest
    assert "transclusion_count: 3" in manifest
