from __future__ import annotations

import math
from pathlib import Path
from typing import Any

from loguru import logger
from PIL import Image

TILE_SIZE = 256
WEBP_QUALITY = 85


def generate_tile_pyramid(
    master_path: Path,
    zone_key: str,
    variant: str,
    config: dict[str, Any],
    out_dir: Path,
) -> int:
    """Slice a master image into a Leaflet-style tile pyramid.

    Returns the total number of tiles written.

    Positive/zero zoom levels are sliced directly from the master image.
    Negative zoom levels are generated by combining 2x2 tiles from the
    level above into one tile (same approach as the old process-tiles.py),
    which preserves aspect ratio correctly for non-square grids.

    Tile Y convention: y=-1 = southernmost (bottom of master),
    y=-num_y = northernmost (top of master).
    """
    max_zoom: int = config["maxZoom"]
    base_x: int = config["baseTilesX"]
    base_y: int = config["baseTilesY"]

    if max(base_x, base_y) > 1:
        min_zoom = -math.ceil(math.log2(max(base_x, base_y)))
    else:
        min_zoom = 0

    img = Image.open(master_path).convert("RGBA")
    zone_dir = out_dir / zone_key
    total = 0

    # --- Positive/zero zoom levels: slice from master ---
    for z in range(max_zoom, -1, -1):
        scale = 2**z
        num_x = base_x * scale
        num_y = base_y * scale

        target_w = num_x * TILE_SIZE
        target_h = num_y * TILE_SIZE

        if target_w > img.width or target_h > img.height:
            continue

        scaled = img.resize((target_w, target_h), Image.LANCZOS)

        for tx in range(num_x):
            for ty in range(num_y):
                tile_y_idx = ty - num_y
                box = (
                    tx * TILE_SIZE,
                    ty * TILE_SIZE,
                    (tx + 1) * TILE_SIZE,
                    (ty + 1) * TILE_SIZE,
                )
                tile = scaled.crop(box)

                tile_dir = zone_dir / str(z) / str(tx)
                tile_dir.mkdir(parents=True, exist_ok=True)
                tile.save(tile_dir / f"{tile_y_idx}.webp", "WEBP", quality=WEBP_QUALITY)
                total += 1

    # --- Negative zoom levels: combine 2x2 from level above ---
    source_tiles_x = base_x
    source_tiles_y = base_y

    for target_zoom in range(-1, min_zoom - 1, -1):
        source_zoom = target_zoom + 1
        source_dir = zone_dir / str(source_zoom)

        out_tiles_x = math.ceil(source_tiles_x / 2)
        out_tiles_y = math.ceil(source_tiles_y / 2)

        target_dir = zone_dir / str(target_zoom)

        for out_x in range(out_tiles_x):
            tile_x_dir = target_dir / str(out_x)
            tile_x_dir.mkdir(parents=True, exist_ok=True)

            for out_y in range(out_tiles_y):
                canvas = Image.new("RGBA", (TILE_SIZE, TILE_SIZE), (0, 0, 0, 0))

                for dx in range(2):
                    for dy in range(2):
                        in_x = out_x * 2 + dx
                        # Source Y index: pair tiles from south (y=-1) to north.
                        # dy=0 → less-negative y (southern of pair) → canvas bottom
                        # dy=1 → more-negative y (northern of pair) → canvas top
                        in_y = -(out_y * 2 + dy + 1)

                        tile_path = source_dir / str(in_x) / f"{in_y}.webp"
                        if not tile_path.exists():
                            continue

                        src_tile = Image.open(tile_path).convert("RGBA")
                        src_tile = src_tile.resize((128, 128), Image.LANCZOS)
                        # dy=0 (south) → bottom half; dy=1 (north) → top half
                        canvas_y = (1 - dy) * 128
                        canvas.paste(src_tile, (dx * 128, canvas_y))

                out_y_idx = -(out_y + 1)
                canvas.save(tile_x_dir / f"{out_y_idx}.webp", "WEBP", quality=WEBP_QUALITY)
                total += 1

        # Next iteration's source grid
        source_tiles_x = out_tiles_x
        source_tiles_y = out_tiles_y

    logger.info(
        f"Generated {total} tiles for {zone_key}/{variant} "
        f"(zoom {min_zoom}..{max_zoom})"
    )
    return total
