SELECT
    i.item_db_index,
    i.id,
    i.stable_key,
    i.display_name,
    i.lore,
    i.required_slot,
    i.this_weapon_type,
    (SELECT GROUP_CONCAT(c.display_name, ', ' ORDER BY c.display_name)
     FROM item_classes ic
     JOIN classes c ON ic.class_name = c.class_name
     WHERE ic.item_stable_key = i.stable_key) AS classes,
    s.quality,
    i.item_level,
    s.hp,
    s.ac,
    s.mana,
    s.str,
    s.end,
    s.dex,
    s.agi,
    s.int,
    s.wis,
    s.cha,
    s.res,
    s.mr,
    s.er,
    s.pr,
    s.vr,
    s.str_scaling,
    s.end_scaling,
    s.dex_scaling,
    s.agi_scaling,
    s.int_scaling,
    s.wis_scaling,
    s.cha_scaling,
    s.resist_scaling,
    s.mitigation_scaling,
    s.weapon_dmg,
    i.weapon_dly,
    i.shield,
    i.weapon_proc_chance,
    i.weapon_proc_on_hit_stable_key,
    i.is_wand,
    i.wand_range,
    i.wand_proc_chance,
    i.wand_effect_stable_key,
    i.is_bow,
    i.bow_effect_stable_key,
    i.bow_proc_chance,
    i.bow_range,
    i.item_effect_on_click_stable_key,
    i.item_skill_use_stable_key,
    i.teach_spell_stable_key,
    i.teach_skill_stable_key,
    i.aura_stable_key,
    i.worn_effect_stable_key,
    i.spell_cast_time,
    i.assign_quest_on_read_stable_key,
    i.complete_on_read_stable_key,
    i.template,
    (SELECT GROUP_CONCAT(material_item_stable_key || ' (x' || material_quantity || ')', ', ')
     FROM crafting_recipes cr
     WHERE cr.recipe_item_stable_key = i.stable_key
     ORDER BY cr.material_slot) AS template_ingredient_stable_keys,
    (SELECT reward_item_stable_key || ' (x' || reward_quantity || ')'
     FROM crafting_rewards crw
     WHERE crw.recipe_item_stable_key = i.stable_key AND crw.reward_slot = 1) AS template_reward_stable_key,
    i.item_value,
    i.sell_value,
    i.stackable,
    i.disposable,
    i.is_unique,
    i.relic,
    i.furniture_set,
    i.no_trade_no_destroy,
    i.book_title,
    i.mining,
    i.fuel_source,
    i.fuel_level,
    i.sim_players_cant_get,
    i.attack_sound_name,
    i.item_icon_name,
    i.equipment_to_activate,
    i.hide_hair_when_equipped,
    i.hide_head_when_equipped,
    i.resource_name
FROM items i
LEFT JOIN item_stats s ON s.item_stable_key = i.stable_key
ORDER BY i.item_db_index,
    CASE s.quality
        WHEN 'Normal' THEN 1
        WHEN 'Blessed' THEN 2
        WHEN 'Godly' THEN 3
        ELSE 4
    END;
