SELECT
    ItemDBIndex,
    Id,
    StableKey,
    ItemName,
    Lore,
    RequiredSlot,
    ThisWeaponType,
    (SELECT GROUP_CONCAT(ClassName, ', ')
     FROM ItemClasses ic
     WHERE ic.ItemStableKey = i.StableKey
     ORDER BY ClassName) AS Classes,
    Quality,
    ItemLevel,
    HP,
    AC,
    Mana,
    Str,
    End,
    Dex,
    Agi,
    Int,
    Wis,
    Cha,
    Res,
    MR,
    ER,
    PR,
    VR,
    StrScaling,
    EndScaling,
    DexScaling,
    AgiScaling,
    IntScaling,
    WisScaling,
    ChaScaling,
    ResistScaling,
    MitigationScaling,
    WeaponDmg,
    WeaponDly,
    Shield,
    WeaponProcChance,
    WeaponProcOnHitStableKey,
    IsWand,
    WandRange,
    WandProcChance,
    WandEffectStableKey,
    --WandBoltColorR,
    --WandBoltColorG,
    --WandBoltColorB,
    --WandBoltColorA,
    --WandBoltSpeed,
    --WandAttackSoundName,
    IsBow,
    BowEffectStableKey,
    BowProcChance,
    BowRange,
    --BowArrowSpeed,
    --BowAttackSoundName,
    ItemEffectOnClickStableKey,
    ItemSkillUseStableKey,
    TeachSpellStableKey,
    TeachSkillStableKey,
    AuraStableKey,
    WornEffectStableKey,
    SpellCastTime,
    AssignQuestOnReadStableKey,
    CompleteOnReadStableKey,
    Template,
    (SELECT GROUP_CONCAT(MaterialItemStableKey || ' (x' || MaterialQuantity || ')', ', ')
     FROM CraftingRecipes cr
     WHERE cr.RecipeItemStableKey = i.StableKey
     ORDER BY cr.MaterialSlot) AS TemplateIngredientStableKeys,
    (SELECT GROUP_CONCAT(RewardItemStableKey || ' (x' || RewardQuantity || ')', ', ')
     FROM CraftingRewards crw
     WHERE crw.RecipeItemStableKey = i.StableKey
     ORDER BY crw.RewardSlot) AS TemplateRewardStableKeys,
    ItemValue,
    SellValue,
    Stackable,
    Disposable,
    "Unique",
    Relic,
    FurnitureSet,
    NoTradeNoDestroy,
    BookTitle,
    Mining,
    FuelSource,
    FuelLevel,
    SimPlayersCantGet,
    AttackSoundName,
    ItemIconName,
    EquipmentToActivate,
    HideHairWhenEquipped,
    HideHeadWhenEquipped,
    ResourceName--,
    --WikiString
FROM items i
LEFT JOIN ItemStats s ON s.ItemStableKey = i.StableKey
ORDER BY i.ItemDBIndex,
    CASE s.Quality
        WHEN 'Normal' THEN 1
        WHEN 'Blessed' THEN 2
        WHEN 'Godly' THEN 3
        ELSE 4
    END;
