SELECT
   -- Identity & Basic Info
   Guid,
   ObjectName,
   NPCName,
   MyWorldFaction,
   MyFaction,
   Level,
   -- Effective Combat Stats (calculated runtime values players encounter)
   EffectiveHP,
   EffectiveAC,
   EffectiveAttackAbility,
   EffectiveBaseAtkDmg,
   EffectiveMinMR,
   EffectiveMaxMR,
   EffectiveMinER,
   EffectiveMaxER,
   EffectiveMinPR,
   EffectiveMaxPR,
   EffectiveMinVR,
   EffectiveMaxVR,
   -- Base Stats (no effective version exists)
   BaseMana,
   BaseStr,
   BaseEnd,
   BaseDex,
   BaseAgi,
   BaseInt,
   BaseWis,
   BaseCha,
   BaseRes,
   RunSpeed,
   BaseLifeSteal,
   BaseMHAtkDelay,
   BaseOHAtkDelay,
   -- XP & Rewards
   BaseXpMin,
   BaseXpMax,
   BossXpMultiplier,
   -- Combat Mechanics
   OHAtkDmg,
   MinAtkDmg,
   DamageRangeMin,
   DamageRangeMax,
   DamageMult,
   ArmorPenMult,
   PowerAttackBaseDmg,
   PowerAttackFreq,
   HealTolerance,
   -- AI Behavior & Movement
   AggroRange,
   AttackRange,
   LeashRange,
   AggressiveTowards,
   Allies,
   Mobile,
   GroupEncounter,
   AggroRegardlessOfLevel,
   -- Spells & Abilities
   AttackSkills,
   AttackSpells,
   BuffSpells,
   HealSpells,
   GroupHealSpells,
   CCSpells,
   TauntSpells,
   PetSpell,
   ProcOnHit,
   ProcOnHitChance,
   -- Special Properties & Quest Integration
   Invulnerable,
   QuestCompleteOnDeath,
   SetAchievementOnDefeat,
   SetAchievementOnSpawn,
   -- Flavor Text & Messages
   AggroMsg,
   AggroEmote,
   SpawnEmote,
   ShoutOnDeath,
   -- Vendor Information
   IsVendor,
   VendorDesc,
   ItemsForSale
FROM Characters;
